### ISSUE TITLE
cpp: gigasecond does not compile

### ISSUE THREAD

**Issue by siebenschlaefer** [exercism/cpp-test-runner#37]
After a student told me about their problems with compiling "gigasecond" in the online editor I took my old correct solution and tried to compile it. I got the error
```
We received the following error when we ran your code:

make: *** No targets specified and no makefile found.  Stop.
```
I don't know the infrastructure well enough to make an educated guess why that error occurs.

If it helps: "gigasecond" is the only exercise that requires an external library: Boost

Let me know if I should provide some more details.

**Comment by peterschussheim** [comment]
@ErikSchierboom:

> Could you perhaps open a PR to add boost to the Dockerfile? I can then test things locally.

Yes, absolutely! I will work on this later today.

**Comment by patricksjackson** [comment]
I don't know anything about Docker, or the test runner, or Alpine, but the boost package that needs to be installed is specifically just the date-time library with dev headers. Min version 1.59 I think, which is many years old at this point.

In Ubuntu, the package name is [libboost-date-time-dev](
https://github.com/exercism/cpp/blob/26352eb5dccf8553228add904ae6aca227e3b07f/.github/workflows/ci.yml#L23). I don't know the corresponding package in Alpine, but you'll need to make sure that the package includes the dev headers as they are often packaged separately.

I can also confirm that this is the only remaining odd dependency that this track has, and it also is necessary for the "meetup" exercise.

**Comment by ErikSchierboom** [comment]
> Yes, absolutely! I will work on this later today.

@peterschussheim Small bump :)

**Comment by peterschussheim** [comment]
@ErikSchierboom Apologies for the delay; I will have a PR for this later today.
